/**
 * @author : tadiewa
 * date: 6/6/2025
 */


package com.tadiewa.smartcv.generator.service;

import com.lowagie.text.Document;
import com.lowagie.text.Font;
import com.lowagie.text.Paragraph;
import com.lowagie.text.pdf.PdfWriter;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import com.lowagie.text.Phrase;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.Rectangle;
import com.lowagie.text.Element;
import java.awt.Color;


public class PdfGeneratorService {
    public static byte[] generatePdfFromText(String title, String content) {
        try (ByteArrayOutputStream outputStream = new ByteArrayOutputStream()) {
            Document document = new Document();
            PdfWriter writer = PdfWriter.getInstance(document, outputStream);
            document.open();

            // Content with a light background
            PdfPTable table = new PdfPTable(1);
            table.setWidthPercentage(100);
            PdfPCell cell = new PdfPCell(new Phrase(content, new Font(Font.HELVETICA, 12, Font.NORMAL, Color.DARK_GRAY)));
            cell.setBackgroundColor(new Color(236, 240, 241)); // Light gray
            cell.setPadding(12f);
            cell.setBorder(Rectangle.NO_BORDER);
            table.addCell(cell);
            document.add(table);

            // Footer
            document.add(new Paragraph("\n"));
            Font footerFont = new Font(Font.HELVETICA, 10, Font.ITALIC, new Color(127, 140, 141));
            Paragraph footer = new Paragraph("Generated by SmartCV", footerFont);
            footer.setAlignment(Element.ALIGN_RIGHT);
            document.add(footer);

            document.close();
            return outputStream.toByteArray();
        } catch (Exception e) {
            throw new RuntimeException("Failed to generate PDF", e);
        }
    }
}
